spring:
  application:
    name: user-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
#spring:
#  application:
#    name: user-service
#  profiles:
#    active: prod
#  cloud:
#    config:
#      enabled: true
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#    import: optional:configserver:http://localhost:8888
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: admin
#    password: admin@123
#  jpa:
#    hibernate:
#      ddl-auto: update
#server:
#  port: 8081
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#    import: optional:configserver:http://localhost:8888
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: admin
#    password: admin@123
#  jpa:
#    hibernate:
#      ddl-auto: validate
#server:
#  port: 8081
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/