spring:
  application:
    name: eureka-server
  profiles:
    active: dev
  cloud:
    config:
      enabled: true
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000

---
#spring:
#  config:
#    activate:
#      on-profile: dev
spring:
  config:
    activate:
      on-profile: dev

# Dev profile keeps default settings
management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  config:
    activate:
      on-profile: prod
  jersey:
    application-path: /eureka/nowhere

eureka:
  dashboard:
    enabled: false
  server:
    enableSelfPreservation: false

management:
  endpoints:
    web:
      exposure:
        include: ''
  endpoint:
    health:
      enabled: false
    info:
      enabled: false